services:
  basicecommerce.webapi:
    image: ${DOCKER_REGISTRY-}basicecommercewebapi
    build:
      context: .
      dockerfile: API/BasicEcommerce.WebAPI/Dockerfile

  basicecommerceapp.presentation:
    image: ${DOCKER_REGISTRY-}basicecommerceapppresentation
    build:
      context: .
      dockerfile: Presentation/BasicEcommerceApp.Presentation/Dockerfile

